fix: remove call to localize on all dates from github
Review-gator started failing when parsing data from github. The
following exception was raised:

ValueError: Not naive datetime (tzinfo is already set)

It seems that all dates now have timezone data (set to UTC). Thus we
don't need to call pytz.utc.localize anymore.